<PSOC_DB>
  <PSOC_PROJECT_LIST>
    <PSOC_PROJECT PATH="\SLC_Free_28_Pin_DIP_LCD_2x_Fix_May_13_2016\SLC_Free_28_Pin_DIP_LCD_2x_Fix_May_13_2016.cmx" IS_ACTIVE="TRUE" />
  </PSOC_PROJECT_LIST>
</PSOC_DB>